#include "p16f1823.inc"

; CONFIG1
; __config 0xFC4
 __CONFIG _CONFIG1, _FOSC_INTOSC & _WDTE_OFF & _PWRTE_ON & _MCLRE_ON & _CP_OFF & _CPD_OFF & _BOREN_ON & _CLKOUTEN_OFF & _IESO_OFF & _FCMEN_OFF
 
; CONFIG2
; __config 0x1DFF
 __CONFIG _CONFIG2, _WRT_OFF & _PLLEN_OFF & _STVREN_OFF & _BORV_LO & _LVP_OFF

 
MEM1	EQU 0x0C
	ORG 0
	GOTO	START
	ORG 4
START
	BANKSEL	OSCCON
	MOVLW	B'0111000'
	BANKSEL	PORTA
	CLRF	PORTA
	BANKSEL	LATA
	CLRF	LATA
	BANKSEL	ANSELA
	CLRF	ANSELA
	BANKSEL	TRISA
	MOVLW	B'11001011'
	MOVWF	TRISA
	
STEP1	
	BANKSEL	PORTA
	MOVLW	B'00110100'
	MOVWF	PORTA
	GOTO STEP1
	
	END